wandb_version: 1

parameters:
  desc: null
  value:
    General:
    - gpu_id
    - use_gpu
    - seed
    - reproducibility
    - state
    - data_path
    - checkpoint_dir
    - show_progress
    - config_file
    - save_dataset
    - dataset_save_path
    - save_dataloaders
    - dataloaders_save_path
    - log_wandb
    Training:
    - epochs
    - train_batch_size
    - learner
    - learning_rate
    - train_neg_sample_args
    - eval_step
    - stopping_step
    - clip_grad_norm
    - weight_decay
    - loss_decimal_place
    Evaluation:
    - eval_args
    - repeatable
    - metrics
    - topk
    - valid_metric
    - valid_metric_bigger
    - eval_batch_size
    - metric_decimal_place
    Dataset:
    - field_separator
    - seq_separator
    - USER_ID_FIELD
    - ITEM_ID_FIELD
    - RATING_FIELD
    - TIME_FIELD
    - seq_len
    - LABEL_FIELD
    - threshold
    - NEG_PREFIX
    - ITEM_LIST_LENGTH_FIELD
    - LIST_SUFFIX
    - MAX_ITEM_LIST_LENGTH
    - POSITION_FIELD
    - HEAD_ENTITY_ID_FIELD
    - TAIL_ENTITY_ID_FIELD
    - RELATION_ID_FIELD
    - ENTITY_ID_FIELD
    - load_col
    - unload_col
    - unused_col
    - additional_feat_suffix
    - rm_dup_inter
    - val_interval
    - filter_inter_by_user_or_item
    - user_inter_num_interval
    - item_inter_num_interval
    - alias_of_user_id
    - alias_of_item_id
    - alias_of_entity_id
    - alias_of_relation_id
    - preload_weight
    - normalize_field
    - normalize_all
    - benchmark_filename
yaml_loader:
  desc: null
  value: yaml.loader.FullLoader
file_config_dict:
  desc: null
  value:
    gpu_id: '0'
    log_wandb: true
    wandb_project: BERT4Rec
    wandb_entity: KactusJec
    wandb_run_name: BERT4Rec NYC
    logging:
      level: DEBUG
    n_layers: 2
    n_heads: 2
    hidden_size: 64
    inner_size: 256
    hidden_dropout_prob: 0.2
    attn_dropout_prob: 0.2
    hidden_act: gelu
    layer_norm_eps: 1.0e-12
    initializer_range: 0.02
    mask_ratio: 0.2
    loss_type: CE
    transform: mask_itemseq
    ft_ratio: 0.5
    checkpoint_dir: SavedData
    save_dataloaders: true
    dataloaders_save_path: ''
    save_dataset: true
    dataset_save_path: SavedData/foursquare_NYC-FourSquare.pth
    seed: 42
    USER_ID_FIELD: user_id
    ITEM_ID_FIELD: venue_id
    TIME_FIELD: timestamp
    LABEL_FIELD: label
    load_col:
      inter:
      - user_id
      - venue_id
      - timestamp
      item:
      - venue_id
      - latitude
      - longitude
      - venue_category_id
    LIST_SUFFIX: _list
    MAX_ITEM_LIST_LENGTH: 32
    ITEM_LIST_LENGTH_FIELD: venue_seq_len
    train_neg_sample_args: null
    dataset: foursquare_NYC
    Use_CustomDataset: true
    Use_CustomSampler: false
    repeatable: true
    model: BERT4Rec
    epochs: 200
    train_batch_size: 8192
    learner: adam
    eval_step: 1
    stopping_step: 10
    single_spec: true
    eval_args:
      order: TO
      spilt:
        RS:
        - 0.7
        - 0.1
        - 0.2
      gourp_by: user_id
      max_seq_len: 32
      mode:
        val: full
        test: full
    metrics:
    - Recall
    - MRR
    - NDCG
    valid_metric: Recall@10
    eval_batch_size: 4096
    weight_decay: 0.01
    topk:
    - 1
    - 5
    - 10
    - 20
variable_config_dict:
  desc: null
  value: {}
cmd_config_dict:
  desc: null
  value: {}
external_config_dict:
  desc: null
  value:
    gpu_id: '0'
    log_wandb: true
    wandb_project: BERT4Rec
    wandb_entity: KactusJec
    wandb_run_name: BERT4Rec NYC
    logging:
      level: DEBUG
    n_layers: 2
    n_heads: 2
    hidden_size: 64
    inner_size: 256
    hidden_dropout_prob: 0.2
    attn_dropout_prob: 0.2
    hidden_act: gelu
    layer_norm_eps: 1.0e-12
    initializer_range: 0.02
    mask_ratio: 0.2
    loss_type: CE
    transform: mask_itemseq
    ft_ratio: 0.5
    checkpoint_dir: SavedData
    save_dataloaders: true
    dataloaders_save_path: ''
    save_dataset: true
    dataset_save_path: SavedData/foursquare_NYC-FourSquare.pth
    seed: 42
    USER_ID_FIELD: user_id
    ITEM_ID_FIELD: venue_id
    TIME_FIELD: timestamp
    LABEL_FIELD: label
    load_col:
      inter:
      - user_id
      - venue_id
      - timestamp
      item:
      - venue_id
      - latitude
      - longitude
      - venue_category_id
    LIST_SUFFIX: _list
    MAX_ITEM_LIST_LENGTH: 32
    ITEM_LIST_LENGTH_FIELD: venue_seq_len
    train_neg_sample_args: null
    dataset: foursquare_NYC
    Use_CustomDataset: true
    Use_CustomSampler: false
    repeatable: true
    model: BERT4Rec
    epochs: 200
    train_batch_size: 8192
    learner: adam
    eval_step: 1
    stopping_step: 10
    single_spec: true
    eval_args:
      order: TO
      spilt:
        RS:
        - 0.7
        - 0.1
        - 0.2
      gourp_by: user_id
      max_seq_len: 32
      mode:
        val: full
        test: full
    metrics:
    - Recall
    - MRR
    - NDCG
    valid_metric: Recall@10
    eval_batch_size: 4096
    weight_decay: 0.01
    topk:
    - 1
    - 5
    - 10
    - 20
model:
  desc: null
  value: BERT4Rec
model_class:
  desc: null
  value: recbole.model.sequential_recommender.bert4rec.BERT4Rec
dataset:
  desc: null
  value: foursquare_NYC
internal_config_dict:
  desc: null
  value:
    gpu_id: '0'
    worker: 0
    use_gpu: true
    seed: 2020
    state: INFO
    reproducibility: true
    data_path: dataset/
    checkpoint_dir: saved
    show_progress: true
    save_dataset: false
    dataset_save_path: null
    save_dataloaders: false
    dataloaders_save_path: null
    log_wandb: false
    wandb_project: recbole
    shuffle: true
    epochs: 300
    train_batch_size: 2048
    learner: adam
    learning_rate: 0.001
    train_neg_sample_args:
      distribution: uniform
      sample_num: 1
      alpha: 1.0
      dynamic: false
      candidate_num: 0
    eval_step: 1
    stopping_step: 10
    clip_grad_norm: null
    weight_decay: 0.0
    loss_decimal_place: 4
    require_pow: false
    enable_amp: false
    enable_scaler: false
    transform: mask_itemseq
    eval_args:
      split:
        LS: valid_and_test
      order: TO
      mode: full
    repeatable: true
    metrics:
    - Recall
    - MRR
    - NDCG
    - Hit
    - Precision
    topk:
    - 10
    valid_metric: MRR@10
    valid_metric_bigger: true
    eval_batch_size: 4096
    metric_decimal_place: 4
    n_layers: 2
    n_heads: 2
    hidden_size: 64
    inner_size: 256
    hidden_dropout_prob: 0.2
    attn_dropout_prob: 0.2
    hidden_act: gelu
    layer_norm_eps: 1.0e-12
    initializer_range: 0.02
    mask_ratio: 0.2
    loss_type: CE
    ft_ratio: 0.5
    field_separator: "\t"
    seq_separator: ' '
    USER_ID_FIELD: user_id
    ITEM_ID_FIELD: item_id
    RATING_FIELD: rating
    TIME_FIELD: timestamp
    seq_len: null
    LABEL_FIELD: label
    threshold: null
    NEG_PREFIX: neg_
    numerical_features: []
    load_col:
      inter:
      - user_id
      - item_id
    unload_col: null
    unused_col: null
    additional_feat_suffix: null
    rm_dup_inter: null
    val_interval: null
    filter_inter_by_user_or_item: true
    user_inter_num_interval: '[0,inf)'
    item_inter_num_interval: '[0,inf)'
    alias_of_user_id: null
    alias_of_item_id: null
    alias_of_entity_id: null
    alias_of_relation_id: null
    preload_weight: null
    normalize_field: null
    normalize_all: null
    discretization: null
    ITEM_LIST_LENGTH_FIELD: item_length
    LIST_SUFFIX: _list
    MAX_ITEM_LIST_LENGTH: 50
    POSITION_FIELD: position_id
    HEAD_ENTITY_ID_FIELD: head_id
    TAIL_ENTITY_ID_FIELD: tail_id
    RELATION_ID_FIELD: relation_id
    ENTITY_ID_FIELD: entity_id
    kg_reverse_r: false
    entity_kg_num_interval: '[0,inf)'
    relation_kg_num_interval: '[0,inf)'
    benchmark_filename: null
    MODEL_TYPE: ModelType.SEQUENTIAL
final_config_dict:
  desc: null
  value:
    gpu_id: '0'
    worker: 0
    use_gpu: true
    seed: 42
    state: INFO
    reproducibility: true
    data_path: dataset/foursquare_NYC
    checkpoint_dir: SavedData
    show_progress: true
    save_dataset: true
    dataset_save_path: SavedData/foursquare_NYC-FourSquare.pth
    save_dataloaders: true
    dataloaders_save_path: ''
    log_wandb: true
    wandb_project: BERT4Rec
    shuffle: true
    epochs: 200
    train_batch_size: 8192
    learner: adam
    learning_rate: 0.001
    train_neg_sample_args:
      distribution: none
      sample_num: none
      alpha: none
      dynamic: false
      candidate_num: 0
    eval_step: 1
    stopping_step: 10
    clip_grad_norm: null
    weight_decay: 0.01
    loss_decimal_place: 4
    require_pow: false
    enable_amp: false
    enable_scaler: false
    transform: mask_itemseq
    eval_args:
      split:
        RS:
        - 0.8
        - 0.1
        - 0.1
      order: TO
      group_by: user
      mode:
        valid: full
        test: full
      spilt:
        RS:
        - 0.7
        - 0.1
        - 0.2
      gourp_by: user_id
      max_seq_len: 32
    repeatable: true
    metrics:
    - Recall
    - MRR
    - NDCG
    topk:
    - 1
    - 5
    - 10
    - 20
    valid_metric: Recall@10
    valid_metric_bigger: true
    eval_batch_size: 4096
    metric_decimal_place: 4
    n_layers: 2
    n_heads: 2
    hidden_size: 64
    inner_size: 256
    hidden_dropout_prob: 0.2
    attn_dropout_prob: 0.2
    hidden_act: gelu
    layer_norm_eps: 1.0e-12
    initializer_range: 0.02
    mask_ratio: 0.2
    loss_type: CE
    ft_ratio: 0.5
    field_separator: "\t"
    seq_separator: ' '
    USER_ID_FIELD: user_id
    ITEM_ID_FIELD: venue_id
    RATING_FIELD: rating
    TIME_FIELD: timestamp
    seq_len: null
    LABEL_FIELD: label
    threshold: null
    NEG_PREFIX: neg_
    numerical_features: []
    load_col:
      inter:
      - user_id
      - venue_id
      - timestamp
      item:
      - venue_id
      - latitude
      - longitude
      - venue_category_id
    unload_col: null
    unused_col: null
    additional_feat_suffix: null
    rm_dup_inter: null
    val_interval: null
    filter_inter_by_user_or_item: true
    user_inter_num_interval: '[0,inf)'
    item_inter_num_interval: '[0,inf)'
    alias_of_user_id: null
    alias_of_item_id: null
    alias_of_entity_id: null
    alias_of_relation_id: null
    preload_weight: null
    normalize_field: null
    normalize_all: null
    discretization: null
    ITEM_LIST_LENGTH_FIELD: venue_seq_len
    LIST_SUFFIX: _list
    MAX_ITEM_LIST_LENGTH: 32
    POSITION_FIELD: position_id
    HEAD_ENTITY_ID_FIELD: head_id
    TAIL_ENTITY_ID_FIELD: tail_id
    RELATION_ID_FIELD: relation_id
    ENTITY_ID_FIELD: entity_id
    kg_reverse_r: false
    entity_kg_num_interval: '[0,inf)'
    relation_kg_num_interval: '[0,inf)'
    benchmark_filename: null
    MODEL_TYPE: ModelType.SEQUENTIAL
    wandb_entity: KactusJec
    wandb_run_name: BERT4Rec NYC
    logging:
      level: DEBUG
    dataset: foursquare_NYC
    Use_CustomDataset: true
    Use_CustomSampler: false
    model: BERT4Rec
    single_spec: true
    MODEL_INPUT_TYPE: InputType.POINTWISE
    eval_type: EvaluatorType.RANKING
    local_rank: 0
    device: cuda
    valid_neg_sample_args:
      distribution: uniform
      sample_num: none
    test_neg_sample_args:
      distribution: uniform
      sample_num: none
    MASK_INDEX: MASK_INDEX
    MASK_ITEM_SEQ: Mask_venue_id_list
    POS_ITEMS: Pos_venue_id
    NEG_ITEMS: Neg_venue_id
_wandb:
  desc: null
  value:
    python_version: 3.8.18
    cli_version: 0.16.3
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1734280809.023053
    t:
      1:
      - 1
      - 5
      - 36
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.8.18
      5: 0.16.3
      8:
      - 1
      - 5
      13: linux-x86_64
